name: .NET Core Build and Restore

on:
  push:
    branches:
      - main
      - Develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use windows-latest or macos-latest depending on your environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust according to your .NET version

    - name: Restore dependencies
      run: |
        cd eBPS.Server  # Navigate to the folder containing the .sln file
        dotnet restore eBPS.Server.sln  # Restore the solution

    - name: Build solution
      run: |
        cd eBPS.Server  # Ensure you're in the correct directory
        dotnet build eBPS.Server.sln --configuration Release  # Build the solution in Release mode

    - name: Run tests
      run: |
        cd eBPS.Server  # Make sure you're in the solution folder
        dotnet test eBPS.Server.sln --configuration Release  # Run tests

    - name: Publish
      run: |
        cd eBPS.Server  # Make sure you're in the solution folder
        dotnet publish eBPS.Server.sln --configuration Release --output ./publish  # Publish the app
